require("libraries/buildinghelper")
require("libraries/keyvalues")
require("game_mode")

if Game == nil then
	Game = class({})
end

function Precache( context )
	PrecacheResource("particle_folder", "particles/buildinghelper", context)

	PrecacheResource("soundfile", "soundevents/game_sounds_items.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sound.vsndevts" , context)
	PrecacheResource("soundfile", "soundevents/music/valve_dota_001/stingers/game_sounds_stingers.vsndevts", context )
	PrecacheResource("soundfile", "soundevents/game_sounds_stingers_diretide.vsndevts", context )
	PrecacheResource("soundfile", "soundevents/game_sounds_roshan_halloween.vsndevts" , context)
	PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_abyssal_underlord.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_alchemist.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_ancient_apparition.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_antimage.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_arc_warden.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_axe.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_bane.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_batrider.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_beastmaster.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_bloodseeker.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_bounty_hunter.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_brewmaster.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_bristleback.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_broodmother.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_centaur.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_chaos_knight.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_chen.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_clinkz.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_crystal_maiden.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_dark_seer.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_dark_willow.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_dazzle.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_death_prophet.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_disruptor.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_doom_bringer.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_dragon_knight.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_drow_ranger.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_earth_spirit.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_earthshaker.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_elder_titan.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_enchantress.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_enigma.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_faceless_void.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_furion.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_grimstroke.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_gyrocopter.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_hoodwink.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_huskar.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_jakiro.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_juggernaut.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_keeper_of_the_light.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_kunkka.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_legion_commander.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_leshrac.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_lich.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_life_stealer.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_lina.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_lion.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_lone_druid.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_luna.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_lycan.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_magnataur.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_mars.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_medusa.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_meepo.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_monkey_king.vsndevts", context)    
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_morphling.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_naga_siren.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_nevermore.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_night_stalker.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_nyx_assassin.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_obsidian_destroyer.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_omniknight.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_oracle.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_pangolier.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_phantom_assassin.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_phoenix.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_puck.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_pudge.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_pugna.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_queenofpain.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_rattletrap.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_razor.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_riki.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_rubick.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_sand_king.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_shadow_demon.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_shadow_shaman.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_shredder.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_silencer.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_skeleton_king.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_skywrath_mage.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_slardar.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_slark.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_snapfire.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_spectre.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_spirit_breaker.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_storm_spirit.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_sven.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_techies.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_templar_assassin.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_terrorblade.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_tidehunter.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_tinker.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_tiny.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_treant.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_troll_warlord.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_tusk.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_undying.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_ursa.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_vengefulspirit.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts", context) 
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_viper.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_visage.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_void_spirit.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_warlock.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_weaver.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_winter_wyvern.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_witch_doctor.vsndevts", context)
    PrecacheResource("soundfile","soundevents/game_sounds_heroes/game_sounds_zuus.vsndevts", context)
end

function Activate()
	game_mode:InitGameMode()
end
